
name: develop
on:
  push:
    branches:
      - develop
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      with:
        registry-type: public

    - name: Extract Metadata for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: public.ecr.aws/k6m5b6e2/dev/blockscout-asc
        tags: |
          type=raw,value={{branch}}-{{sha}}-{{date 'x'}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./docker/Dockerfile
        push: true
        platforms: linux/amd64
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        build-args: |
          CACHE_EXCHANGE_RATES_PERIOD=
          DISABLE_READ_API=false
          API_PATH=/
          NETWORK_PATH=/
          DISABLE_WEBAPP=false
          DISABLE_WRITE_API=false
          CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
          CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
          SOCKET_ROOT=
          WOBSERVER_ENABLED=false
          ADMIN_PANEL_ENABLED=
